### ISSUE TITLE
rust-lld: error: --shared-memory is disallowed

### ISSUE THREAD

**Issue by mensch272** [Amanieu/parking_lot#308]
I'm getting linking errors when trying to compile `parking_lot` to wasm32

```
error: linking with `rust-lld` failed: exit code: 1
...
= note: rust-lld: error: mutable global exported but 'mutable-globals' feature not present in inputs: `__tls_base`. Use --no-check-features to suppress.
          rust-lld: error: mutable global exported but 'mutable-globals' feature not present in inputs: `__tls_size`. Use --no-check-features to suppress.
          rust-lld: error: mutable global exported but 'mutable-globals' feature not present in inputs: `__tls_align`. Use --no-check-features to suppress.
          rust-lld: error: --shared-memory is disallowed by parking_lot-895c1fa325be9efc.parking_lot.9358177a-cgu.5.rcgu.o because it was not compiled with 'atomics' or 'bulk-memory' features.
          rust-lld: error: 'bulk-memory' feature must be used in order to use shared memory
```

### Build

rustflags = "-Ctarget-feature=+atomics"
version = rustc 1.59.0-nightly (404c8471a 2021-12-14)

**Comment by bjorn3** [comment]
You must always combine the atomics target feature with the mutable-globals and bulk-memory target features, so `-Ctarget-feature=+atomics,+mutable-globals,+bulk-memory`. Also make sure to enable them for all crates including the standard library if you don't already do this. Doing this requires `-Zbuild-std`. Not doing this may cause corruption due to the standard library thinking that it will only run single threaded and thus not using atomics where necessary.

**Comment by mensch272** [comment]
Using those flags gave me a bunch of errors saying `doesn't have a size known at compile-time`.

**Comment by bjorn3** [comment]
Can you link to the full compilation log somewhere? That may make it easier to find the issue.

**Comment by mensch272** [comment]
### Command

```
cargo build --lib --target wasm32-unknown-unknown -Z build-std
```

### Config

<details>
<summary>Cargo.toml</summary>

```toml
[package]
name = "chapturn-sources-wasm"
version = "0.1.0"
authors = ["Mensch272 <47662901+mensch272@users.noreply.github.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = { version = "0.2.78", features = ["serde-serialize"] }
chapturn-sources = { path = "../chapturn-sources" }
chrono = { version = "0.4.19", features = ["serde", "wasmbind"] }
serde = "1.0.130"

parking_lot = { version = "0.11", features = ["nightly"] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.dev]
opt-level = 2
incremental = true

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
lto = true
```
</details>

<details>
<summary>.cargo/config.toml</summary>

```toml
[build]
rustflags = ["-Ctarget-feature=+atomics,+mutable-globals,+bulk-memory"]
```
</details>

[output.txt](https://github.com/Amanieu/parking_lot/files/7721364/output.txt)
