### ISSUE TITLE
Inconsistent error with parking_lot in wasm32

### ISSUE THREAD

**Issue by KivalM** [Amanieu/parking_lot#351]
Hey, so I am working with a library that depends on parking_lot in a WASM  environment, and every so often (maybe 1 out of 50 runs), I will experience this error.

``` 'Parking not supported on this platform'```

parking_lot_core-0.9.3/src/thread_parker/wasm.rs:26:9

It is just weird because this happens inconsistently and is impossible to reproduce. Is there any particular reason the program would throw this error seemingly randomly?

I am using 
```toml
parking_lot = { version = "0.12", features = ["nightly"] }
```

**Comment by Amanieu** [comment]
Have you read [this section](https://github.com/Amanieu/parking_lot#nightly-vs-stable) of the README?

**Comment by KivalM** [comment]
Yes, My `.cargo/config.toml` looks like this

```toml
[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+atomics,+bulk-memory,+mutable-globals", "-C", "link-arg=--max-memory=4294967296"]

[unstable]
build-std = ["panic_abort", "std"]

[build]
target = "wasm32-unknown-unknown"
```

And I am running rust nightly-2022-04-07

Both of the above mainly due to [wasm-bindgen-rayon](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon) requirements
